### ISSUE TITLE
When POSTing forms: undefined method `turbo_stream_action_tag' for Turbo::StreamsHelper:Module

### ISSUE THREAD

**Issue by randomsnowflake** [cmer/ultimate_turbo_modal-rails#5]
I want to show a form as a modal, and also as a normal page.

This simple code fails during runtime with the exception from the title:

```ruby
<%= modal(advance: false, title:) do %>
```

It fails in [lib/ultimate_turbo_modal/base.rb:55 ](https://github.com/search?q=repo%3Acmer%2Fultimate_turbo_modal-rails+turbo_stream_action_tag&type=code) (see attached stacktrace)

The modal code works in my form, when it is ...
- executed as a "popup" modal
- loaded through normal page navigation 

It does not work, when ...
- the form is reloaded after an invalid form submission (using Turbo)
- the form is reloaded after a POST request to the server

I'm using the newest version of Rails & Co. Turbo works fine in my app.

See my [Gemfile.lock](https://github.com/cmer/ultimate_turbo_modal-rails/files/13667512/Gemfile.lock.txt)

Also: [stacktrace.txt](https://github.com/cmer/ultimate_turbo_modal-rails/files/13667604/stacktrace.txt)

**Comment by randomsnowflake** [comment]
In case anybody else needs the fix:

```ruby
# application_helper.rb

	def mymodal(**options, &block)
		begin
			modal(**options, &block)
		rescue => e
			capture(&block)
		end
	end
```

**Comment by muriloime** [comment]
@cmer First of all , nice solution , I am still studying it to try to make it more general, I was looking for such a solution for a long time. 

Secondly, Is the proposed solution a good one? If so , why not to put it into the gem ?  

I am also receiving this error, and can help with a PR

**Comment by cmer** [comment]
Let me investigate this further I never saw this before.
