### ISSUE TITLE
Typo when importing Idiomorph library in application.js

### ISSUE THREAD

**Issue by cavenk** [cmer/ultimate_turbo_modal-rails#6]
There is a typo when configuring Idiomorph in application.js. 
The key should be 'morphStyle' in camel case. 
See screenshot below.
<img width="919" alt="Screenshot 2024-01-25 at 12 00 27 PM" src="https://github.com/cmer/ultimate_turbo_modal-rails/assets/92652455/1314eec3-2cb8-40dc-9a10-cf7920ed984c">

With the typo, this option is ignored and the default 'outerHTML' option is used. 
This creates sometimes a problem with Turbo because when I press a link and I receive the response as turbo, Idiomorph will try to merge the new content with the old turbo frametag by comparing the attributes of the element. However, Turbo automatically adds and removes some attributes on the turbo frame tag like 'src' or 'completed' while Idiomorph is running and this creates an error because Idiomorph is not able to compare the attributes
<img width="1308" alt="Screenshot 2024-01-25 at 1 23 01 PM" src="https://github.com/cmer/ultimate_turbo_modal-rails/assets/92652455/d4a3dbce-b842-4580-9cf3-d0b7e7763862">

If I set the morphStyle to 'innerHTML', there is another problem. The turbo frame tag is put inside of the original turbo frame tag and there is now multiple turbo frame tag with the same name
<img width="995" alt="Screenshot 2024-01-25 at 1 24 54 PM" src="https://github.com/cmer/ultimate_turbo_modal-rails/assets/92652455/c8887584-e306-4655-8c32-f5215ab3d147">

**Comment by cmer** [comment]
I have fixed the typo. Thanks for letting me know!

Regarding the Idiomorph issue, it seems to be a bug on their end. I'm not sure what to do about it. I have already reported it, and found a workaround: https://github.com/bigskysoftware/idiomorph/issues/41
