### ISSUE TITLE
Stimulus modal naming colission with flowbite library

### ISSUE THREAD

**Issue by cavenk** [cmer/ultimate_turbo_modal-rails#7]
I am using Flowbite which is a library build on top of Tailwind. When using the ultimate turbo modal, I receive this error: 
<img width="995" alt="Screenshot 2024-01-25 at 1 32 04 PM" src="https://github.com/cmer/ultimate_turbo_modal-rails/assets/92652455/93fd313c-51a8-44fe-8b09-480133f87b0a">

This is because your library and flowbite have the same naming for the modal controller. A possible solution would be renaming the stimulus controller to 'ultimate-turbo-modal'

**Comment by cmer** [comment]
I'll consider this for a future release. Thanks.
