### ISSUE TITLE
 Error: Cannot find module 'ultimate_turbo_modal/gemPath'

### ISSUE THREAD

**Issue by enrique-fernandez-polo** [cmer/ultimate_turbo_modal-rails#8]
Hello!!

I am using the tailwind flavor and I getting the following error on startup.

```bash
Error: Cannot find module 'ultimate_turbo_modal/gemPath'
```

I have the `ultimate_turbo_modal` dependency in my `package.json` file and I am using other JS libraries without any issue.

Any ideas?? Thanks!

EDIT: This way works

```javascript
const { execSync } = require("child_process");

function getUltimateTurboModalPath() {
  const path = execSync("bundle show ultimate_turbo_modal").toString().trim();
  return `${path}/**/*.{erb,html,rb}`;
}
```

**Comment by kinduff** [comment]
Had this same error and the fix you proposed worked for me too.
